# Generated by Django 6.0.3 on 2026-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="User", max_length=150, verbose_name="Ник"),
        ),
    ]
