# Generated by Django 6.0.3 on 2026-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место выполнения привычки", max_length=100
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        help_text="Время выполнения привычки", max_length=50
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие — привычка в одном предложении",
                        max_length=255,
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Приятная привычка, признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Ежедневно"),
                            (2, "Через день"),
                            (3, "1 раз в три дня"),
                            (4, "1 раз в четыре дня"),
                            (5, "1 раз в пять дней"),
                            (6, "1 раз в шесть дней"),
                            (7, "1 раз в семь дней"),
                        ],
                        default=1,
                        help_text="Периодичность выполнения (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение после выполнения",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=120, help_text="Время на выполнение привычки в секундах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Привычка доступна публично"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
